name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  JAVA_VERSION: 11

jobs:
  build:
    runs-on: ubuntu-latest
    services:

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Change permissions
        run: chmod +x ./mvnw
      - name: Maven Clean install
        run: ./mvnw --no-transfer-progress clean install